# Generated by Django 5.0.1 on 2026-02-11 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.CharField(choices=[('EXCELLENT', 'Excellent Offer'), ('GOOD', 'Good Offer'), ('FAIR', 'Fair Offer'), ('POOR', 'Below Market')], max_length=10)),
                ('analysis_score', models.FloatField(help_text='0-100 score indicating bid quality')),
                ('suggested_counter_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('negotiation_tips', models.JSONField(default=list, help_text='List of negotiation talking points')),
                ('strengths', models.JSONField(default=list, help_text='Positive aspects of the bid')),
                ('weaknesses', models.JSONField(default=list, help_text='Concerns about the bid')),
                ('reasoning', models.TextField(help_text='AI detailed analysis')),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Accept'), ('COUNTER', 'Counter Offer'), ('REJECT', 'Reject'), ('NEGOTIATE', 'Negotiate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='market.bid')),
            ],
            options={
                'verbose_name_plural': 'Bid Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_min_price', models.DecimalField(decimal_places=2, help_text='AI suggested minimum price per quintal', max_digits=10)),
                ('recommended_max_price', models.DecimalField(decimal_places=2, help_text='AI suggested maximum price per quintal', max_digits=10)),
                ('optimal_price', models.DecimalField(decimal_places=2, help_text='AI optimal/target price per quintal', max_digits=10)),
                ('confidence_score', models.FloatField(help_text='Confidence level 0-1')),
                ('reasoning', models.TextField(help_text='AI explanation for the recommendation')),
                ('market_factors', models.JSONField(default=dict, help_text='Market conditions considered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_recommendations', to='market.croplisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_quintals', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Standard'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='STANDARD', max_length=20)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('foreign_matter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cropvariety')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_prices', to='market.order')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.region')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['crop_variety', 'state', 'transaction_date'], name='ai_assistan_crop_va_e8a540_idx'), models.Index(fields=['transaction_date'], name='ai_assistan_transac_7621b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50)),
                ('current_avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_trend', models.CharField(choices=[('RISING', 'Rising'), ('STABLE', 'Stable'), ('FALLING', 'Falling')], max_length=20)),
                ('trend_percentage', models.DecimalField(decimal_places=2, help_text='% change from previous period', max_digits=5)),
                ('insights', models.TextField(help_text='AI-generated market insights')),
                ('recommendations', models.JSONField(default=list, help_text='Key recommendations for farmers')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data_points_count', models.IntegerField(default=0, help_text='Number of transactions analyzed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cropvariety')),
            ],
            options={
                'verbose_name_plural': 'Market Intelligence',
                'ordering': ['-created_at'],
                'unique_together': {('crop_variety', 'state', 'period_start', 'period_end')},
            },
        ),
    ]
