from django.db import models
from django.conf import settings
from market.models import CropListing, Bid
from core.models import CropVariety, Region


class PriceRecommendation(models.Model):
    """
    Stores AI-generated price recommendations for crop listings.
    """
    listing = models.ForeignKey(CropListing, on_delete=models.CASCADE, related_name='price_recommendations')
    
    recommended_min_price = models.DecimalField(max_digits=10, decimal_places=2, help_text="AI suggested minimum price per quintal")
    recommended_max_price = models.DecimalField(max_digits=10, decimal_places=2, help_text="AI suggested maximum price per quintal")
    optimal_price = models.DecimalField(max_digits=10, decimal_places=2, help_text="AI optimal/target price per quintal")
    
    confidence_score = models.FloatField(help_text="Confidence level 0-1")
    reasoning = models.TextField(help_text="AI explanation for the recommendation")
    market_factors = models.JSONField(default=dict, help_text="Market conditions considered")
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"Price Rec for Listing #{self.listing.id} - ₹{self.optimal_price}"


class BidAnalysis(models.Model):
    """
    AI analysis of incoming bids to help farmers make decisions.
    """
    class Quality(models.TextChoices):
        EXCELLENT = 'EXCELLENT', 'Excellent Offer'
        GOOD = 'GOOD', 'Good Offer'
        FAIR = 'FAIR', 'Fair Offer'
        POOR = 'POOR', 'Below Market'
    
    bid = models.OneToOneField(Bid, on_delete=models.CASCADE, related_name='ai_analysis')
    
    quality_rating = models.CharField(max_length=10, choices=Quality.choices)
    analysis_score = models.FloatField(help_text="0-100 score indicating bid quality")
    
    suggested_counter_offer = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    
    negotiation_tips = models.JSONField(default=list, help_text="List of negotiation talking points")
    strengths = models.JSONField(default=list, help_text="Positive aspects of the bid")
    weaknesses = models.JSONField(default=list, help_text="Concerns about the bid")
    
    reasoning = models.TextField(help_text="AI detailed analysis")
    recommendation = models.CharField(max_length=20, choices=[
        ('ACCEPT', 'Accept'),
        ('COUNTER', 'Counter Offer'),
        ('REJECT', 'Reject'),
        ('NEGOTIATE', 'Negotiate')
    ])
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = "Bid Analyses"
        ordering = ['-created_at']
    
    def __str__(self):
        return f"Analysis for Bid #{self.bid.id} - {self.quality_rating}"


class HistoricalPrice(models.Model):
    """
    Tracks historical transaction prices for market intelligence and trends.
    """
    crop_variety = models.ForeignKey(CropVariety, on_delete=models.PROTECT)
    region = models.ForeignKey(Region, on_delete=models.PROTECT, null=True, blank=True)
    
    # Geographic details
    district = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    
    # Price data
    price_per_quintal = models.DecimalField(max_digits=10, decimal_places=2)
    quantity_quintals = models.DecimalField(max_digits=10, decimal_places=2)
    
    # Quality indicators
    quality_grade = models.CharField(max_length=20, choices=[
        ('PREMIUM', 'Premium'),
        ('STANDARD', 'Standard'),
        ('FAIR', 'Fair'),
        ('POOR', 'Poor')
    ], default='STANDARD')
    moisture_content = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    foreign_matter = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    
    # Transaction details
    transaction_date = models.DateField()
    order = models.ForeignKey('market.Order', on_delete=models.SET_NULL, null=True, blank=True, related_name='historical_prices')
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-transaction_date']
        indexes = [
            models.Index(fields=['crop_variety', 'state', 'transaction_date']),
            models.Index(fields=['transaction_date']),
        ]
    
    def __str__(self):
        return f"{self.crop_variety.name} - ₹{self.price_per_quintal} ({self.transaction_date})"


class MarketIntelligence(models.Model):
    """
    Aggregated market insights and trends generated by AI.
    """
    crop_variety = models.ForeignKey(CropVariety, on_delete=models.CASCADE)
    state = models.CharField(max_length=50, blank=True)
    
    # Trend data
    current_avg_price = models.DecimalField(max_digits=10, decimal_places=2)
    price_trend = models.CharField(max_length=20, choices=[
        ('RISING', 'Rising'),
        ('STABLE', 'Stable'),
        ('FALLING', 'Falling')
    ])
    trend_percentage = models.DecimalField(max_digits=5, decimal_places=2, help_text="% change from previous period")
    
    # Insights
    insights = models.TextField(help_text="AI-generated market insights")
    recommendations = models.JSONField(default=list, help_text="Key recommendations for farmers")
    
    # Metadata
    period_start = models.DateField()
    period_end = models.DateField()
    data_points_count = models.IntegerField(default=0, help_text="Number of transactions analyzed")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ['crop_variety', 'state', 'period_start', 'period_end']
        verbose_name_plural = "Market Intelligence"
    
    def __str__(self):
        return f"{self.crop_variety.name} - {self.price_trend} (₹{self.current_avg_price})"
