# Generated by Django 5.0.1 on 2026-02-04 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_quintals', models.DecimalField(decimal_places=2, help_text='Quantity in quintals (100kg)', max_digits=10)),
                ('expected_price_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_description', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, help_text='Moisture %', max_digits=5, null=True)),
                ('foreign_matter', models.DecimalField(blank=True, decimal_places=2, help_text='Foreign matter %', max_digits=5, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cropvariety')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_quintal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='market.croplisting')),
            ],
            options={
                'ordering': ['-amount_per_quintal', '-created_at'],
                'unique_together': {('listing', 'buyer')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('TOKEN_DEPOSITED', 'Token Deposited (20%)'), ('FULL_DEPOSITED', 'Full Amount in Escrow'), ('RELEASED', 'Released to Farmer'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('order_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='market.bid')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.croplisting')),
            ],
        ),
    ]
